# Countermovement Jump (CMJ, no arm swing)

In [2]:
import pandas as pd
import os

In [3]:
cmj = pd.read_csv('countermovement_dl.csv')

Filter out arm swing Jumps

In [4]:
cmj_no_armswing = cmj[cmj['tags'].apply(lambda x: 'CMJ with Arm Swing' not in x)]

Pull necessary columns: 
['athlete id', 'athlete name', 'id', 'mRSI',
       'segment', 'tags', 'timestamp', 'injured', 'Jump Height(m)']

In [5]:
default = ['athlete id', 'athlete name', 'id', 'mRSI', 'segment', 'tags', 'timestamp', 'injured', 'Jump Height(m)', 
           'Peak Relative Propulsive Power(W/k.g)', 'System Weight(N)']

def best_jump(df, cols=default):
    df = df[cols]
    df = df.sort_values(by=['Jump Height(m)'], ascending=False).drop_duplicates(subset=['id'], keep='first')
    return df.drop_duplicates(subset=['athlete id'], keep='first')

Create seperate table with the highest jumps from that day. This will be used as the 'best trial' of the day

In [6]:
cmj_best = best_jump(cmj_no_armswing)
cmj_best.head()

,athlete id,athlete name,id,mRSI,segment,tags,timestamp,injured,Jump Height(m),Peak Relative Propulsive Power(W/k.g),System Weight(N)
41,85YcBTVSBbXufLek7O10,Lauren Green,0V7Ua8pMvdHwhZnGtVoB,0.68,1,[],1562628496,0,0.52,66,1131
31,0Wd7zQnaEe27svzN67db,Aarslan Rafique,U0Gkij1FNlMX5ZgAW8vC,0.34,2,['Injury'],1560364033,1,0.34,48,711
13,AkRhBIuX4rjzWpX8HoFx,Sydney Tekstra,polJvrS7zoJmVfUS83uA,0.38,18,[],1558453339,0,0.33,46,698
27,oCndOH4Zywp9Rwahs6XW,Lizzie Dolan,md7C3qGOhEGQq9qQtsPP,0.38,3,['Injury'],1560184782,1,0.32,49,626
72,kIq7pK9NZ6pusgUpCUcF,Kelvin Uribe,FKcik5x3JE3KSQWnJ9Gg,0.53,1,['Injury'],1559147239,1,0.32,53,730

#### Chart 1 - Jump Height vs mRSI (modified Reactive Strength Index) 

Chart Type: Time series (categorical) 

Description: Using the best trial of the day (based on highest jump height), display how that jump compared to past trials. Simultaneously show the quality (mRSI) of each jump compared to previous. Needs to clearly display worthwhile change (standard error or deviation). 

Purpose: 
* Show variation in jump performance over time (jump height) 
* Show variation in jump quality for each jump (mRSI)

In [9]:
c1_cols = ['athlete id', 'athlete name', 'id', 'mRSI','Jump Height(m)', 'System Weight(N)', 'timestamp', 'tags']
c1 = cmj_best[c1_cols]
c1.head()

,athlete id,athlete name,id,mRSI,Jump Height(m),System Weight(N),timestamp,tags
41,85YcBTVSBbXufLek7O10,Lauren Green,0V7Ua8pMvdHwhZnGtVoB,0.68,0.52,1131,1562628496,[]
31,0Wd7zQnaEe27svzN67db,Aarslan Rafique,U0Gkij1FNlMX5ZgAW8vC,0.34,0.34,711,1560364033,['Injury']
13,AkRhBIuX4rjzWpX8HoFx,Sydney Tekstra,polJvrS7zoJmVfUS83uA,0.38,0.33,698,1558453339,[]
27,oCndOH4Zywp9Rwahs6XW,Lizzie Dolan,md7C3qGOhEGQq9qQtsPP,0.38,0.32,626,1560184782,['Injury']
72,kIq7pK9NZ6pusgUpCUcF,Kelvin Uribe,FKcik5x3JE3KSQWnJ9Gg,0.53,0.32,730,1559147239,['Injury']

#### Chart 2 – Relative Peak Propulsive Power 

Chart Type: Time series (categorical) 

Description: Using the best trial of the day (based on highest jump height), display how much power was produced relative to the athlete’s weight 

Purpose: 
* Display how Power production is trending over time

In [11]:
c2_cols = ['athlete id', 'athlete name', 'id', 'Peak Relative Propulsive Power(W/k.g)', 'System Weight(N)', 'timestamp', 'tags']
c2 = cmj_best[c2_cols]
c2.head()

,athlete id,athlete name,id,Peak Relative Propulsive Power(W/k.g),System Weight(N),timestamp,tags
41,85YcBTVSBbXufLek7O10,Lauren Green,0V7Ua8pMvdHwhZnGtVoB,66,1131,1562628496,[]
31,0Wd7zQnaEe27svzN67db,Aarslan Rafique,U0Gkij1FNlMX5ZgAW8vC,48,711,1560364033,['Injury']
13,AkRhBIuX4rjzWpX8HoFx,Sydney Tekstra,polJvrS7zoJmVfUS83uA,46,698,1558453339,[]
27,oCndOH4Zywp9Rwahs6XW,Lizzie Dolan,md7C3qGOhEGQq9qQtsPP,49,626,1560184782,['Injury']
72,kIq7pK9NZ6pusgUpCUcF,Kelvin Uribe,FKcik5x3JE3KSQWnJ9Gg,53,730,1559147239,['Injury']

### Export to CSV

In [12]:
# can change the names of these later if needed
csv_list = ['c1.csv', 'c2.csv']
df_list = [c1, c2]

for i in range(len(csv_list)):
    csv = csv_list[i]
    curr_df = df_list[i] 
    if not os.path.isfile(csv):
        curr_df.to_csv(csv, header='column_names')
    else: # else it exists so append without writing the header
        curr_df.to_csv(csv, mode='a', header=False)